version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/bugbuster
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=tuClaveSegura
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=bugbuster
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"