spring.application.name=bugbuster

# --- CONFIGURACIÓN POSTGRESQL (Render Internal) ---
spring.datasource.url=jdbc:postgresql://bugbuster_db_user:OFX390v89bOzwrLqU06YbRev6PSKvkjo@dpg-dag9k42d0e5s73ai6qjg-a/bugbuster_db
spring.datasource.username=bugbuster_db_user
spring.datasource.password=OFX390v89bOzwrLqU06YbRev6PSKvkjo
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate
# 'update' crea las tablas automáticamente en PostgreSQL si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET:tuClaveSuperSecretaParaJWT1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Desactivamos H2 Console porque ya no usamos H2
spring.h2.console.enabled=false
