spring.application.name=bugbuster

# --- CONFIGURACIÓN POSTGRESQL (Limpia y Optimizada) ---
spring.datasource.url=jdbc:postgresql://dpg-dag9k42d0e5s73ai6qjg-a/bugbuster_db
spring.datasource.username=bugbuster_db_user
spring.datasource.password=OFX390v89bOzwrLqU06YbRev6PSKvkjo
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# CORRECCIÓN DE ADVERTENCIAS (Warnings)
# 1. Quitamos el dialecto explícito porque Hibernate lo detecta solo (Soluciona el WARN del Dialecto)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect <-- ELIMINADO

# 2. Desactivamos Open-In-View para mejorar rendimiento y limpiar logs (Soluciona el WARN de JpaWebConfiguration)
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:tuClaveSuperSecretaParaJWT1234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Desactivar H2 por completo
spring.h2.console.enabled=false
